<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="title" content="Login">
    <meta name="description" content="Pantalla de acceso al sistema de pago">
    <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="all" />
    <link rel="stylesheet" href="/css/estilos.css" type="text/css" media="all" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/basico.js"></script>
  </head>
  <body>
    <div class="container">
      <div class="card login-card col-md-6">
        <div class="card-body">
          <h1 class="display-4"><?=$titulo_respuesta?></h1>
          <p class="lead"><?=$informacion?></p>
          <a class="btn btn-primary btn-lg" href="#" role="button">Aceptar</a>
        </div>
      </div>
    </div>
  </body>
</html>
