<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="title" content="Pago online">
    <meta name="description" content="Pantalla para realizar pagos online">
    <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="all" />
    <link rel="stylesheet" href="/css/estilos.css" type="text/css" media="all" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/basico.js"></script>
  </head>
  <body>
    <div class="container">
      <div class="card pago-card col-md-8">
        <div class="card-body">
          <h5 class="card-title">Sistema de pago con tarjetas</h5>
          <form>
            <!-- Campos ocultos -->

            <!-- Campos visuales -->
            <div class="form-group">
              <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Preference</label>
              <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                <option selected value="N" hidden>Tipo de tarjeta...</option>
                <option value="V">Visa</option>
                <option value="MC">MasterCard</option>
                <option value="AE">AmericanExpress</option>
              </select>
            </div>
            <div class="form-row tipos">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="usuario">Número de tarjeta</label>
                  <input type="text" class="form-control" id="num-tarjeta" placeholder="Número de tarjeta" value="">
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <label for="usuario">Código de seguridad</label>
                  <input type="text" class="form-control" id="num-tarjeta" placeholder="Código" value="">
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <label for="usuario">Vencimiento</label>
                  <input type="date" class="form-control" id="num-tarjeta" placeholder="Vencimiento" value="">
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-danger" id="btn-cancelar">Cancelar</button>
            <button type="button" class="btn btn-success" id="btn-procesar">Procesar</button>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>
